### ISSUE TITLE
[OPL]TidyUpのスコアシートのつけ方について

### ISSUE THREAD

**Issue by IS0moto** [RoboCupAtHomeJP/AtHome2024#24]
RCJ24 TUのルールの更新に伴い，[スコアシート](https://docs.google.com/spreadsheets/d/1Dn0LTINAVYMcSL2Yoqi4iicPZOmU6h8e/edit?usp=sharing&ouid=115914283332872721627&rtpof=true&sd=true)について以下の3つの提案を行います．
・Drop，Hitの項目の削除（ルールにないため．）
・サンプルページの追加（新規参入チームのスコアシートの使用方法学習．DSPL-TUのルールとの勘違い防止）
・各タスク項目にリスタートタイミングをつけるチェックボックスを設ける（リスタートタイミングの明確化）

**Comment by MrKeith99** [comment]
@IS0moto さん，返事が遅くなり，申し訳ございません．
2022年度のScore Sheetは使わない予定です．
次のReleaseにすべとの競技のScore Sheetを共有する予定ですが，現時点のTidy UpのScore Sheetを添付しておきます．
ご参考までお願いします．
[RCJ2024_OPL_TU_採点表.pdf](https://github.com/RoboCupAtHomeJP/AtHome2024/files/14884123/RCJ2024_OPL_TU_.pdf)
