### ISSUE TITLE
[OPL]TUのタスク２におけるスコアについて

### ISSUE THREAD

**Issue by IS0moto** [RoboCupAtHomeJP/AtHome2024#25]
タスク２のスコアが入るタイミングのアクションの中で，障害物に衝突することなくRoom 2: Dining Roomに入った後，**物体を提供する**で30点獲得となっており，ご記載だと思われる．

**Comment by MrKeith99** [comment]
@IS0moto さん，ご指摘，ありがとうございます．
そのとおりで，`物体を提供する`という部分は見出しのため，`30点`は付きません．
次のReleaseまでに修正します．
